import 'package:journal/recipe.dart';

List<Recipe> dummyRecipes = [
  Recipe(
    id: 'r1',
    title: 'Spaghetti with Tomato Sauce',
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Spaghetti_al_rag%C3%B9_-_Gastronomic_event_at_Veggiano_2011.jpg/800px-Spaghetti_al_rag%C3%B9_-_Gastronomic_event_at_Veggiano_2011.jpg',
    ingredients: [
      '400g spaghetti',
      '1 can (400g) crushed tomatoes',
      '2 cloves garlic, minced',
      '1 onion, chopped',
      '2 tbsp olive oil',
      'Salt and pepper to taste',
      'Fresh basil for garnish',
    ],
    instructions: [
      'Cook spaghetti according to package directions.',
      'In a large pan, heat olive oil over medium heat. Add onion and cook until softened, about 5 minutes.',
      'Add garlic and cook for 1 minute more until fragrant.',
      'Stir in crushed tomatoes, salt, and pepper. Bring to a simmer and cook for 15-20 minutes, stirring occasionally.',
      'Drain spaghetti and add to the sauce, tossing to combine.',
      'Serve hot, garnished with fresh basil.',
    ],
    duration: 30,
    complexity: Complexity.simple,
  ),
  Recipe(
    id: 'r2',
    title: 'Classic Margherita Pizza',
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/a/a2/Pizza_Margherita_-_Naples_2017.jpg',
    ingredients: [
      '1 pizza dough',
      '1/2 cup tomato sauce',
      '150g fresh mozzarella, sliced',
      'Fresh basil leaves',
      '1 tbsp olive oil',
      'Pinch of salt',
    ],
    instructions: [
      'Preheat oven to 220°C (425°F).',
      'On a lightly floured surface, roll out the pizza dough to your desired thickness.',
      'Spread tomato sauce evenly over the dough, leaving a small border for the crust.',
      'Arrange mozzarella slices over the sauce.',
      'Bake for 10-15 minutes, or until the crust is golden brown and the cheese is bubbly and slightly browned.',
      'Remove from oven, drizzle with olive oil, sprinkle with salt, and scatter fresh basil leaves over the top.',
      'Slice and serve immediately.',
    ],
    duration: 25,
    complexity: Complexity.simple,
  ),
  Recipe(
    id: 'r3',
    title: 'Chicken Stir-fry',
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/e/e0/Stir_Fry_Chicken.jpg',
    ingredients: [
      '500g chicken breast, sliced',
      '1 tbsp soy sauce',
      '1 tbsp cornstarch',
      '2 tbsp vegetable oil',
      '1 onion, sliced',
      '1 bell pepper, sliced',
      '1 cup broccoli florets',
      '1 carrot, julienned',
      '2 cloves garlic, minced',
      '1 tbsp ginger, grated',
      'Stir-fry sauce (e.g., soy sauce, sesame oil, honey, rice vinegar)',
    ],
    instructions: [
      'In a bowl, toss chicken with soy sauce and cornstarch. Set aside for 10 minutes.',
      'Heat 1 tbsp vegetable oil in a large wok or pan over high heat. Add chicken and stir-fry until cooked through. Remove chicken from pan and set aside.',
      'Add remaining 1 tbsp vegetable oil to the pan. Add onion, bell pepper, broccoli, and carrot. Stir-fry for 3-5 minutes until vegetables are crisp-tender.',
      'Add garlic and ginger and cook for 1 minute more until fragrant.',
      'Return chicken to the pan. Pour in stir-fry sauce and toss to coat everything evenly. Cook for 1-2 minutes until sauce thickens slightly.',
      'Serve hot with rice or noodles.',
    ],
    duration: 35,
    complexity: Complexity.medium,
  ),
  Recipe(
    id: 'r4',
    title: 'Vegetable Lasagna',
    imageUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/b3/Lasagna_vegetariana_%285038595304%29.jpg',
    ingredients: [
      '12 lasagna noodles',
      '1 tbsp olive oil',
      '1 onion, chopped',
      '2 cloves garlic, minced',
      '1 zucchini, diced',
      '1 bell pepper, diced',
      '1 cup spinach, chopped',
      '1 can (400g) crushed tomatoes',
      '1 cup ricotta cheese',
      '1/2 cup grated Parmesan cheese',
      '1 egg',
      'Salt, pepper, and oregano to taste',
      '2 cups shredded mozzarella cheese',
    ],
    instructions: [
      'Preheat oven to 190°C (375°F). Cook lasagna noodles according to package directions until al dente. Drain and set aside.',
      'In a large pan, heat olive oil over medium heat. Add onion and cook until softened, about 5 minutes.',
      'Add garlic, zucchini, and bell pepper. Cook for 5-7 minutes until vegetables are tender-crisp.',
      'Stir in spinach and crushed tomatoes. Simmer for 10 minutes, stirring occasionally.',
      'In a separate bowl, combine ricotta cheese, Parmesan cheese, egg, salt, pepper, and oregano.',
      'Spread a thin layer of vegetable sauce on the bottom of a 9x13 inch baking dish.',
      'Arrange a layer of cooked lasagna noodles over the sauce. Spread half of the ricotta mixture over the noodles, then top with a layer of vegetable sauce and a sprinkle of mozzarella.',
      'Repeat layers, finishing with noodles, remaining vegetable sauce, and a generous layer of mozzarella cheese.',
      'Cover with foil and bake for 25 minutes. Remove foil and bake for another 10-15 minutes, or until cheese is golden and bubbly.',
      'Let stand for 10 minutes before slicing and serving.',
    ],
    duration: 60,
    complexity: Complexity.complex,
  ),
];
